apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # username: superman@google.com
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # password: root123
  PG_PASSWORD: cm9vdDEyMw0K
